'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8806
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")>  _
Partial Friend NotInheritable Class ConnString
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As ConnString = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New ConnString),ConnString)
    
    Public Shared ReadOnly Property [Default]() As ConnString
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SERVER=192.168.1.5; DATABASE=EmployerLodgingAndDeductions;user id=sa;password=SAd"& _ 
        "min55;Connect Timeout=300")>  _
    Public Property Conn() As String
        Get
            Return CType(Me("Conn"),String)
        End Get
        Set
            Me("Conn") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SERVER=192.168.1.5; DATABASE=Funeral Policy Master;user id=sa;password=SAdmin55;C"& _ 
        "onnect Timeout=300")>  _
    Public Property ConnFPM() As String
        Get
            Return CType(Me("ConnFPM"),String)
        End Get
        Set
            Me("ConnFPM") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SERVER=192.168.1.5; DATABASE=MicroLoansMaster_new_MLM;user id=sa;password=SAdmin5"& _ 
        "5;Connect Timeout=300")>  _
    Public Property ConnMLMAdvances() As String
        Get
            Return CType(Me("ConnMLMAdvances"),String)
        End Get
        Set
            Me("ConnMLMAdvances") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SERVER=192.168.1.5; DATABASE=Recharge Master_Orange;user id=sa;password=SAdmin55;"& _ 
        "Connect Timeout=300")>  _
    Public Property ConnRMOrange() As String
        Get
            Return CType(Me("ConnRMOrange"),String)
        End Get
        Set
            Me("ConnRMOrange") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SERVER=192.168.1.5; DATABASE=Recharge Master_BeMobile;user id=sa;password=SAdmin5"& _ 
        "5;Connect Timeout=300")>  _
    Public Property ConnRMBeMobile() As String
        Get
            Return CType(Me("ConnRMBeMobile"),String)
        End Get
        Set
            Me("ConnRMBeMobile") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SERVER=192.168.1.5; DATABASE=Funeral Policy Master;user id=sa;password=SAdmin55;C"& _ 
        "onnect Timeout=300")>  _
    Public Property ConnFPMLocal() As String
        Get
            Return CType(Me("ConnFPMLocal"),String)
        End Get
        Set
            Me("ConnFPMLocal") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SERVER=192.168.1.5; DATABASE=MicroLoansMaster_new_MLM;user id=sa;password=SAdmin5"& _ 
        "5;Connect Timeout=300")>  _
    Public Property ConnMLMLocalAdvances() As String
        Get
            Return CType(Me("ConnMLMLocalAdvances"),String)
        End Get
        Set
            Me("ConnMLMLocalAdvances") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SERVER=192.168.1.5; DATABASE=Recharge Master_Orange;user id=sa;password=SAdmin55;"& _ 
        "Connect Timeout=300")>  _
    Public Property ConnRMOrangeLocal() As String
        Get
            Return CType(Me("ConnRMOrangeLocal"),String)
        End Get
        Set
            Me("ConnRMOrangeLocal") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SERVER=192.168.1.5; DATABASE=Recharge Master_BeMobile;user id=sa;password=SAdmin5"& _ 
        "5;Connect Timeout=300")>  _
    Public Property ConnRMBeMobileLocal() As String
        Get
            Return CType(Me("ConnRMBeMobileLocal"),String)
        End Get
        Set
            Me("ConnRMBeMobileLocal") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SERVER=192.168.1.5; DATABASE=EmployerLodgingAndDeductions;user id=sa;password=SAd"& _ 
        "min55;Connect Timeout=300")>  _
    Public Property ConnLocal() As String
        Get
            Return CType(Me("ConnLocal"),String)
        End Get
        Set
            Me("ConnLocal") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SERVER=192.168.1.5; DATABASE=MicroLoansMaster_Educational;user id=sa;password=SAd"& _ 
        "min55;Connect Timeout=300")>  _
    Public Property ConnMLMEducational() As String
        Get
            Return CType(Me("ConnMLMEducational"),String)
        End Get
        Set
            Me("ConnMLMEducational") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SERVER=192.168.1.5; DATABASE=MicroLoansMaster_Educational;user id=sa;password=SAd"& _ 
        "min55;Connect Timeout=300")>  _
    Public Property ConnMLMLocalEducational() As String
        Get
            Return CType(Me("ConnMLMLocalEducational"),String)
        End Get
        Set
            Me("ConnMLMLocalEducational") = value
        End Set
    End Property
End Class
